---
# tasks file for apache

- name: install apache
  apt: pkg=apache2 state=present update_cache=true

# Apache Configuration
- name: Create document root
  file:
    path: "/var/www/{{ domain_name }}"
    state: directory
    owner: "www-data"
    group: "www-data"
    mode: '0755'

- name: Set up Apache VirtualHost
  template:
    src: "files/apache.conf.j2"
    dest: "/etc/apache2/sites-available/{{ domain_name }}.conf"
  notify: Reload Apache

- name: Enable rewrite module
  shell: /usr/sbin/a2enmod rewrite
  notify: Reload Apache

- name: Enable new site
  shell: /usr/sbin/a2ensite {{ domain_name }}.conf
  notify: Reload Apache

- name: Enable ports 80 and 443 in Firewall
  ufw:
    rule: allow
    name: 'Apache Full'