---
# tasks file for googlechrome - Ubuntu

- name: Add gpg signing key for {{ googlechrome_app_name }}.
  apt_key:
    url: "{{ googlechrome_gpg_key }}"
    state: present
- name: Adding repository {{ googlechrome_repo_debian }} on Debian based systems.
  apt_repository:
    repo: "{{ googlechrome_repo_debian }}"
    state: "{{ googlechrome_repo_desired_state }}"
    filename: "{{ googlechrome_repo_debian_filename }}"
    update_cache: yes
- name: Installing {{ googlechrome_app_name }} on Debian based systems.
  apt:
    name: "{{ googlechrome_app_name }}"
    state: "{{ googlechrome_desired_state }}"
    force_apt_get: yes
    update_cache: yes
