---
# tasks file for geerlingguy.mysql

- name: Install MySQL Packages
  apt:
    pkg: ['mysql-server']
    state: present
    update_cache: true

# MySQL Configuration
- name: Copy mysqld.cnf
  template:
    src: "files/mysqld.cnf.j2"
    dest: "/etc/mysql/mysql.conf.d/mysqld.cnf"
  notify:
    - Restart mysql

- name: configure MySQL
  mysql_root_password: "{{ mysql_root_password }}"
  mysql_databases:
    - name: example_db
      encoding: latin1
      collation: latin1_general_ci
  mysql_users:
    - name: example_user
      host: "%"
      password: "similarly-secure-password"
      priv: "example_db.*:ALL"
#
#- name: Set the root password
#  #ignore_errors: yes
#  mysql_user:
#    name: root
#    host_all: yes
#    check_implicit_admin: yes
#    password: "{{ mysql_root_password }}"
#    #login_unix_socket: /var/run/mysqld/mysqld.sock
#    login_user: root
#    login_password: "{{ mysql_root_password }}"
#
#- name: Create dbAdmin account
#  mysql_user:
#    name: dbAdmin
#    host_all: yes
#    check_implicit_admin: yes
#    password: "{{ mysql_root_password }}"
#    state: present
#    login_user: root
#    login_password: "{{ mysql_root_password }}"
#    login_host: '{{ ansible_host }}'
#    #login_unix_socket: /var/run/mysqld/mysqld.sock

# - name: Remove all anonymous user accounts
#   mysql_user:
#     name: ''
#     host_all: yes
#     #check_implicit_admin: yes
#     state: absent
#     login_user: root
#     login_password: "{{ mysql_root_password }}"
#     #login_host: "{{ private_ip }}"
#
# - name: Remove the MySQL test database
#   mysql_db:
#     name: test
#     state: absent
#     check_implicit_admin: yes
#     login_user: root
#     login_password: "{{ mysql_root_password }}"
#     #login_host: "{{ private_ip }}"





