---
- name: Perform Safe Upgrade
  apt: upgrade=safe update_cache=yes

- name: Install Server Basics
  apt:
    pkg: ['acl', 'apt-listchanges', 'apt-show-versions', 'apt-transport-https', 'aptitude', 'clamav', 'clamav-daemon', 'unattended-upgrades', 'policykit-1', 'ntp','wget', 'curl', 'vim', 'ack-grep', 'git', 'unzip', 'htop', 'tmux', 'rsync', 'lftp', 'curl','net-tools', 'acct', 'lynis', 'debsecan', 'sysstat']
    state: present
    update_cache: true
  notify:
    - Start NTP

- name: Add Periodic Configuration
  copy: src=10periodic dest=/etc/apt/apt.conf.d/10periodic owner=root group=root

- name: Add Unattended Upgrade Configuration
  copy: src=50unattended-upgrades dest=/etc/apt/apt.conf.d/50unattended-upgrades owner=root group=root
  notify:
   - Restart Unattended Upgrades

- name: change hostname
  hostname:
    name: "{{ domain_name }}"

- name: add hostname to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1[ \t]+localhost'
    line: '127.0.0.1 localhost {{ domain_name }}'
    state: present