---
galaxy_info:
  role_name: googlechrome
  author: Ali Muhammad
  description: Google Chrome stable version installation or uninstallation in Debian/EL based systems with amd64 architecture.
  company: none
  license: MIT
  min_ansible_version: 2.4

  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic
    - name: Debian
      versions:
        - stretch
        - buster
    - name: EL
      versions:
        - 7

  galaxy_tags:
    - googlechrome
    - os
    - system
    - web
    - browsers

dependencies: []
